-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity run_writeOutcome is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    errorInTask_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    errorInTask_ce0 : OUT STD_LOGIC;
    errorInTask_we0 : OUT STD_LOGIC;
    errorInTask_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    errorInTask1 : IN STD_LOGIC_VECTOR (3 downto 0);
    checkId : IN STD_LOGIC_VECTOR (7 downto 0);
    taskId : IN STD_LOGIC_VECTOR (7 downto 0);
    uniId : IN STD_LOGIC_VECTOR (15 downto 0);
    error : IN STD_LOGIC_VECTOR (0 downto 0);
    toScheduler_TDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    toScheduler_TVALID : OUT STD_LOGIC;
    toScheduler_TREADY : IN STD_LOGIC;
    outcomeInRam_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    outcomeInRam_ce0 : OUT STD_LOGIC;
    outcomeInRam_we0 : OUT STD_LOGIC_VECTOR (35 downto 0);
    outcomeInRam_d0 : OUT STD_LOGIC_VECTOR (287 downto 0);
    p_read : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read4 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read5 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read6 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read7 : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of run_writeOutcome is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv64_2 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000010";
    constant ap_const_lv64_3 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000011";
    constant ap_const_lv64_4 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000100";
    constant ap_const_lv64_5 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000101";
    constant ap_const_lv64_6 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000110";
    constant ap_const_lv64_7 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000111";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv36_0 : STD_LOGIC_VECTOR (35 downto 0) := "000000000000000000000000000000000000";
    constant ap_const_lv36_FFFFFFFFD : STD_LOGIC_VECTOR (35 downto 0) := "111111111111111111111111111111111101";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal toScheduler_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal errorInTask1_cast_fu_306_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal errorInTask1_cast_reg_472 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal exitcond4_fu_323_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal outcome_AOV_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal outcome_AOV_load_reg_490 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal outcome_AOV_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal outcome_AOV_load_1_reg_495 : STD_LOGIC_VECTOR (31 downto 0);
    signal outcome_AOV_load_2_reg_510 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal outcome_AOV_load_3_reg_515 : STD_LOGIC_VECTOR (31 downto 0);
    signal outcome_AOV_load_4_reg_530 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal outcome_AOV_load_5_reg_535 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal outcome_AOV_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal outcome_AOV_ce0 : STD_LOGIC;
    signal outcome_AOV_we0 : STD_LOGIC;
    signal outcome_AOV_address1 : STD_LOGIC_VECTOR (2 downto 0);
    signal outcome_AOV_ce1 : STD_LOGIC;
    signal loop_index3_cast_fu_318_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal loop_index3_fu_106 : STD_LOGIC_VECTOR (3 downto 0);
    signal empty_fu_329_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_state7 : BOOLEAN;
    signal ap_block_state7_io : BOOLEAN;
    signal tmp_fu_335_p10 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal empty_61_fu_377_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_60_fu_373_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_59_fu_370_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_58_fu_367_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_57_fu_364_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_56_fu_361_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_55_fu_358_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_54_fu_355_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component run_mux_84_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        din6_WIDTH : INTEGER;
        din7_WIDTH : INTEGER;
        din8_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        din4 : IN STD_LOGIC_VECTOR (31 downto 0);
        din5 : IN STD_LOGIC_VECTOR (31 downto 0);
        din6 : IN STD_LOGIC_VECTOR (31 downto 0);
        din7 : IN STD_LOGIC_VECTOR (31 downto 0);
        din8 : IN STD_LOGIC_VECTOR (3 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component run_writeOutcome_outcome_AOV_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    outcome_AOV_U : component run_writeOutcome_outcome_AOV_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => outcome_AOV_address0,
        ce0 => outcome_AOV_ce0,
        we0 => outcome_AOV_we0,
        d0 => tmp_fu_335_p10,
        q0 => outcome_AOV_q0,
        address1 => outcome_AOV_address1,
        ce1 => outcome_AOV_ce1,
        q1 => outcome_AOV_q1);

    mux_84_32_1_1_U144 : component run_mux_84_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 32,
        din5_WIDTH => 32,
        din6_WIDTH => 32,
        din7_WIDTH => 32,
        din8_WIDTH => 4,
        dout_WIDTH => 32)
    port map (
        din0 => p_read,
        din1 => p_read1,
        din2 => p_read2,
        din3 => p_read3,
        din4 => p_read4,
        din5 => p_read5,
        din6 => p_read6,
        din7 => p_read7,
        din8 => loop_index3_fu_106,
        dout => tmp_fu_335_p10);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    loop_index3_fu_106_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                loop_index3_fu_106 <= ap_const_lv4_0;
            elsif (((exitcond4_fu_323_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                loop_index3_fu_106 <= empty_fu_329_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                    errorInTask1_cast_reg_472(3 downto 0) <= errorInTask1_cast_fu_306_p1(3 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                outcome_AOV_load_1_reg_495 <= outcome_AOV_q0;
                outcome_AOV_load_reg_490 <= outcome_AOV_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                outcome_AOV_load_2_reg_510 <= outcome_AOV_q0;
                outcome_AOV_load_3_reg_515 <= outcome_AOV_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                outcome_AOV_load_4_reg_530 <= outcome_AOV_q0;
                outcome_AOV_load_5_reg_535 <= outcome_AOV_q1;
            end if;
        end if;
    end process;
    errorInTask1_cast_reg_472(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, error, toScheduler_TREADY, ap_CS_fsm_state7, ap_CS_fsm_state2, exitcond4_fu_323_p2, ap_block_state7_io)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((exitcond4_fu_323_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                if ((not(((ap_const_boolean_1 = ap_block_state7_io) or ((error = ap_const_lv1_1) and (toScheduler_TREADY = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;

    ap_ST_fsm_state7_blk_assign_proc : process(error, toScheduler_TREADY, ap_block_state7_io)
    begin
        if (((ap_const_boolean_1 = ap_block_state7_io) or ((error = ap_const_lv1_1) and (toScheduler_TREADY = ap_const_logic_0)))) then 
            ap_ST_fsm_state7_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state7_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state8_blk <= ap_const_logic_0;

    ap_block_state7_assign_proc : process(error, toScheduler_TREADY)
    begin
                ap_block_state7 <= ((error = ap_const_lv1_1) and (toScheduler_TREADY = ap_const_logic_0));
    end process;


    ap_block_state7_io_assign_proc : process(error, toScheduler_TREADY)
    begin
                ap_block_state7_io <= ((error = ap_const_lv1_1) and (toScheduler_TREADY = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state8)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    empty_54_fu_355_p1 <= outcome_AOV_load_reg_490;
    empty_55_fu_358_p1 <= outcome_AOV_load_1_reg_495;
    empty_56_fu_361_p1 <= outcome_AOV_load_2_reg_510;
    empty_57_fu_364_p1 <= outcome_AOV_load_3_reg_515;
    empty_58_fu_367_p1 <= outcome_AOV_load_4_reg_530;
    empty_59_fu_370_p1 <= outcome_AOV_load_5_reg_535;
    empty_60_fu_373_p1 <= outcome_AOV_q0;
    empty_61_fu_377_p1 <= outcome_AOV_q1;
    empty_fu_329_p2 <= std_logic_vector(unsigned(loop_index3_fu_106) + unsigned(ap_const_lv4_1));
    errorInTask1_cast_fu_306_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(errorInTask1),64));
    errorInTask_address0 <= errorInTask1_cast_reg_472(4 - 1 downto 0);

    errorInTask_ce0_assign_proc : process(error, toScheduler_TREADY, ap_CS_fsm_state7, ap_block_state7_io, ap_CS_fsm_state8)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) or (not(((ap_const_boolean_1 = ap_block_state7_io) or ((error = ap_const_lv1_1) and (toScheduler_TREADY = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state7)))) then 
            errorInTask_ce0 <= ap_const_logic_1;
        else 
            errorInTask_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    errorInTask_d0 <= ap_const_lv1_1;

    errorInTask_we0_assign_proc : process(error, toScheduler_TREADY, ap_CS_fsm_state7, ap_block_state7_io)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state7_io) or ((error = ap_const_lv1_1) and (toScheduler_TREADY = ap_const_logic_0)))) and (error = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            errorInTask_we0 <= ap_const_logic_1;
        else 
            errorInTask_we0 <= ap_const_logic_0;
        end if; 
    end process;

    exitcond4_fu_323_p2 <= "1" when (loop_index3_fu_106 = ap_const_lv4_8) else "0";
    loop_index3_cast_fu_318_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(loop_index3_fu_106),64));
    outcomeInRam_address0 <= ap_const_lv64_0(4 - 1 downto 0);

    outcomeInRam_ce0_assign_proc : process(error, toScheduler_TREADY, ap_CS_fsm_state7, ap_CS_fsm_state6, ap_block_state7_io)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (not(((ap_const_boolean_1 = ap_block_state7_io) or ((error = ap_const_lv1_1) and (toScheduler_TREADY = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state7)))) then 
            outcomeInRam_ce0 <= ap_const_logic_1;
        else 
            outcomeInRam_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    outcomeInRam_d0 <= ((((((((((empty_61_fu_377_p1 & empty_60_fu_373_p1) & empty_59_fu_370_p1) & empty_58_fu_367_p1) & empty_57_fu_364_p1) & empty_56_fu_361_p1) & empty_55_fu_358_p1) & empty_54_fu_355_p1) & uniId) & ap_const_lv8_0) & checkId);

    outcomeInRam_we0_assign_proc : process(ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            outcomeInRam_we0 <= ap_const_lv36_FFFFFFFFD;
        else 
            outcomeInRam_we0 <= ap_const_lv36_0;
        end if; 
    end process;


    outcome_AOV_address0_assign_proc : process(ap_CS_fsm_state2, exitcond4_fu_323_p2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, loop_index3_cast_fu_318_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            outcome_AOV_address0 <= ap_const_lv64_6(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            outcome_AOV_address0 <= ap_const_lv64_4(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            outcome_AOV_address0 <= ap_const_lv64_2(3 - 1 downto 0);
        elsif (((exitcond4_fu_323_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            outcome_AOV_address0 <= ap_const_lv64_1(3 - 1 downto 0);
        elsif (((exitcond4_fu_323_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            outcome_AOV_address0 <= loop_index3_cast_fu_318_p1(3 - 1 downto 0);
        else 
            outcome_AOV_address0 <= "XXX";
        end if; 
    end process;


    outcome_AOV_address1_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            outcome_AOV_address1 <= ap_const_lv64_7(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            outcome_AOV_address1 <= ap_const_lv64_5(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            outcome_AOV_address1 <= ap_const_lv64_3(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            outcome_AOV_address1 <= ap_const_lv64_0(3 - 1 downto 0);
        else 
            outcome_AOV_address1 <= "XXX";
        end if; 
    end process;


    outcome_AOV_ce0_assign_proc : process(ap_CS_fsm_state2, exitcond4_fu_323_p2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or ((exitcond4_fu_323_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((exitcond4_fu_323_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            outcome_AOV_ce0 <= ap_const_logic_1;
        else 
            outcome_AOV_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    outcome_AOV_ce1_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            outcome_AOV_ce1 <= ap_const_logic_1;
        else 
            outcome_AOV_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    outcome_AOV_we0_assign_proc : process(ap_CS_fsm_state2, exitcond4_fu_323_p2)
    begin
        if (((exitcond4_fu_323_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            outcome_AOV_we0 <= ap_const_logic_1;
        else 
            outcome_AOV_we0 <= ap_const_logic_0;
        end if; 
    end process;

    toScheduler_TDATA <= taskId;

    toScheduler_TDATA_blk_n_assign_proc : process(error, toScheduler_TREADY, ap_CS_fsm_state7)
    begin
        if (((error = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            toScheduler_TDATA_blk_n <= toScheduler_TREADY;
        else 
            toScheduler_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    toScheduler_TVALID_assign_proc : process(error, toScheduler_TREADY, ap_CS_fsm_state7, ap_block_state7_io)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state7_io) or ((error = ap_const_lv1_1) and (toScheduler_TREADY = ap_const_logic_0)))) and (error = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            toScheduler_TVALID <= ap_const_logic_1;
        else 
            toScheduler_TVALID <= ap_const_logic_0;
        end if; 
    end process;

end behav;
